import { describe, it, expect } from 'vitest';

/**
 * Koans: Utility Types
 * 
 * TypeScript provides built-in utilities to transform types.
 * Common ones include Partial, Pick, Omit, and Readonly.
 */

describe('05_utilities.test.ts', () => {
  interface User {
    id: number;
    name: string;
    email: string;
  }

  it('Partial<T> makes all properties optional', () => {
    // Useful for update operations where you might only update some fields.
    const updateDTO: Partial<User> = {
      email: "new@example.com"
    };

    // TODO: Fix the expectation
    expect(updateDTO.id).toBe(0);
  });

  it('Pick<T, K> selects specific properties', () => {
    // Only 'id' and 'name' are allowed. 'email' is excluded.
    type UserPreview = Pick<User, "id" | "name">;

    const preview: UserPreview = {
      id: 1,
      name: "Alice"
      // email: "alice@example.com" // This would be a compile error
    };

    // TODO: Fix the expectation
    expect(preview.name).toBe("");
  });

  it('Omit<T, K> removes specific properties', () => {
    // Removes 'id' from User. Useful for creation DTOs where ID is generated by DB.
    type CreateUserDTO = Omit<User, "id">;

    const newUser: CreateUserDTO = {
      name: "Bob",
      email: "bob@example.com"
    };

    // TODO: Fix the expectation
    expect(newUser.email).toBe("");
  });

  it('Readonly<T> makes properties immutable', () => {
    const user: Readonly<User> = {
      id: 1,
      name: "Charlie",
      email: "charlie@example.com"
    };

    // user.name = "Dave"; // This would be a compile error

    // TODO: Fix the expectation
    expect(user.name).toBe("");
  });
});
